### PR TITLE
Fix link to training data

### PR DESCRIPTION
**Pull request by cn4750**
Update to our new storage server.

### CODE REVIEW

**Review by Naphthalin — CHANGES_REQUESTED** [review]
I would suggest to link to `https://storage.lczero.org/files/` directly, as it saves a click. What do you think?

**Comment by cn4750** [comment]
> 
> 
> I would suggest to link to `https://storage.lczero.org/files/` directly, as it saves a click. What do you think?

I agree. Added.

**Comment by Naphthalin** [comment]
http instead of https, and the missing / in the end are intentional?

**Comment by cn4750** [comment]
> 
> 
> http instead of https, and the missing / in the end are intentional?

Both are not required, but I've changed it either way.

**Review by Naphthalin — APPROVED** [review]

**Pull request merged**
